name: CI

on:
  pull_request:
    branches:
      - 'release_*x'

jobs:
  linux:
    strategy:
      matrix:
        architecture:
          - '[{"name": "AArch64", "runner": "ubuntu-24.04-arm"}]'
          - '[{"name": "X86", "runner": "ubuntu-24.04"}]'
    uses: ./.github/workflows/flang-tests.yml
    with:
      architecture: ${{ matrix.architecture }}
    secrets: inherit
