name: Build and test Flang

on:
  workflow_call:
    inputs:
      architecture:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.target.runner }}
    env:
      install_prefix: /usr/local
    strategy:
      matrix:
        target: ${{ fromJSON(inputs.architecture) }}
        tool:
          - {"cc": "clang-17", "cxx": "clang++-17"}
          - {"cc": "clang-18", "cxx": "clang++-18"}
          - {"cc": "gcc-13", "cxx": "g++-13"}
    steps:
      - uses: actions/checkout@v7

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: key-${{ matrix.cc }}-${{ matrix.version }}

      - name: Check tools
        run: |
          git --version
          cmake --version
          make --version
          ${{ matrix.tool.cc }} --version
          ${{ matrix.tool.cxx }} --version

      - name: Build Clang/LLVM
        run: ./build-llvm-project.sh -t ${{ matrix.target.name }} -p ${{ env.install_prefix }} -a /usr/bin/${{ matrix.tool.cc }} -b /usr/bin/${{ matrix.tool.cxx }} -n $(nproc) -c -i -s -x "-DLLVM_ENABLE_ASSERTIONS=ON" -v

      - name: Checkout Flang
        run: |
          cd ../..
          git clone --depth 1 --single-branch --branch master https://github.com/flang-compiler/flang.git

      - name: Build libpgmath and Flang
        run: |
          cd ../../flang
          ./build-flang.sh -t ${{ matrix.target.name }} -p ${{ env.install_prefix }} -n $(nproc) -s -l $(realpath ../classic-flang-llvm-project/classic-flang-llvm-project/llvm)

      - name: Copy llvm-lit
        run: |
          cd ../../flang
          cp ../classic-flang-llvm-project/classic-flang-llvm-project/build/bin/llvm-lit build/flang/bin/

      - name: Test Flang
        run: |
          cd ../../flang/build/flang
          make check-all
